### ISSUE TITLE
Create Blood Pressure percentile calculator

### ISSUE THREAD

**Issue by mrueschman** [sleepepi/patstrial.org#26]
Like this one: https://www.bcm.edu/bodycomplab/Flashapps/BPVAgeChartpage.html (reference for data tables cited)

This issue is similar to #1 and perhaps it would make the most sense to include the calculators on the same page since things like gender and age are both applicable.

**Comment by remomueller** [comment]
More information on page 47: http://www.nhlbi.nih.gov/files/docs/resources/heart/hbp_ped.pdf

**Comment by remomueller** [comment]
Did this ended up being needed or can we close this issue?
