### ISSUE TITLE
Have DSMB member sign-off ballot associated with certain documents on site

### ISSUE THREAD

**Issue by mrueschman** [sleepepi/patstrial.org#41]
From first DSMB meeting bullets:

> The DSMB requests quarterly reports sent electronically to all DSMB members with an email ballot with the following options: A) continue trial or B) schedule a call to discuss.

Mostly making this issue to keep this in mind. I would like to discuss with the group whether simply doing this by email would be more straightforward.

**Comment by remomueller** [comment]
Closing issue, no longer needed.
