### ISSUE TITLE
Create more prominent link to BMI z-score calculator

### ISSUE THREAD

**Issue by mrueschman** [sleepepi/patstrial.org#49]
This will probably be the primary reason people are visiting the site as the study goes on. Ideally people could easily get to it from both logged out and logged in statuses. 

(Links are provided on Slice Designs, but people will have the mindset "1) go to patstrial.org; 2) locate calculator).

**Comment by remomueller** [comment]
Closing as existing flow seems sufficient, and also keeping the target audience for the website users who review the aggregate data, as opposed to those entering individual level data.
