### ISSUE TITLE
Directory of Site Personnel

### ISSUE THREAD

**Issue by remomueller** [sleepepi/patstrial.org#5]
Provide ability to list site personnel, role, email, and phone.

@mrueschman should we add "blinded"/"unblinded" status here as well?
- [x] Editors should be able to create and update directory listings
- [x] Viewers should be able to see the `/directory` from their dashboard
- [x] Directory listings are grouped by site

**Comment by mrueschman** [comment]
Nah, I don't think blinded status would add anything useful.
