### ISSUE TITLE
Add demographics report

### ISSUE THREAD

**Issue by mrueschman** [sleepepi/patstrial.org#53]
Forging ahead with pulling data from Slice and reporting on patstrial.org, we could do something with the demographic variables on the CIW:
- Age: `ciw_age_years` (numeric)
- Sex: `ciw_sex` (1=Male; 2=Female)
- Ethnicity: `ciw_ethnicity` (1=Hispanic or Latino; 2=Not Hispanic or Latino)
- Race: `ciw_race` (checkboxes)

We would want to be able to breakdown by Screened/Consented/Eligible/Randomized and then by Overall/Individual Sites.

I don't think a time/chronological aspect is needed in a Demographics report (at least in the first year or more of the study).

**Comment by remomueller** [comment]
- [x] Put in navigation from "Screened" back to "Demographics"
- [x] Allow filtering by `Screened`, `Consented`, `Eligible`, and `Randomized`
- [x] Add bar chart for age at top
- [x] Add pie chart for gender at top
- [x] Collapse race into three categories
- [x] Split large table into multiple tables
- [x] Add percentages into table
- [x] Use `text-muted` for "Unknown" categories
