### ISSUE TITLE
Add new reports about data integrity / quality

### ISSUE THREAD

**Issue by mrueschman** [sleepepi/patstrial.org#59]
Placeholder issue for now -- will be thinking about this.

**Comment by mrueschman** [comment]
At today's PATS meeting we discussed adding some signal-specific quality charts/figures. Signals of interest likely include capnography, chest, snore, and an EEG channel (e.g. E1).

I think best approach would be to make this page -- https://patstrial.org/reports/data-quality -- into a "PSG Data Quality page and add some signal-specific numbers on there. We can keep the overall quality chart that we have already.

@remomueller Should we arbitrarily choose some date/time in the future to roll this out? Sometime later this month or March? I can provide context on Slice variables.

**Comment by remomueller** [comment]
Yes, this could be included in v0.49.0 of Slice
