### ISSUE TITLE
Add gender/race/ethnicity report for consented subjects

### ISSUE THREAD

**Issue by mrueschman** [sleepepi/patstrial.org#65]
Create tables that mimic the below. These are useful for IRB Continuing Review and NIH Progress reports, which sites will generate regularly over the course of the study.

![image](https://cloud.githubusercontent.com/assets/707167/17785537/3d690b7a-654f-11e6-86fc-b1a42135517a.png)

Variables of interest on CIW:
- ciw_complete_informed_consent (indicates subjects to keep)
- ciw_sex
- ciw_ethnicity
- ciw_race__1 (.. 2, 3, 4, 5, 6)

**Comment by remomueller** [comment]
@mrueschman is this covered already in the existing updates, or any need to add this at the current time?

**Comment by mrueschman** [comment]
Seems to have been covered in existing updates!
