### ISSUE TITLE
Add a new AE report that displays 

### ISSUE THREAD

**Issue by remomueller** [sleepepi/patstrial.org#71]
![screen shot 2017-05-09 at 11 39 42 am](https://cloud.githubusercontent.com/assets/316479/25859343/3d6ebcfa-34ac-11e7-80c7-926c174357ba.png)

The rows would be per site with a Total Adverse Events footer (total)

**Comment by remomueller** [comment]
cc @mrueschman any updates on if this should be added?

**Comment by mrueschman** [comment]
I think we can forego this issue for now. Maybe for a project that is more AE-focused (like LOFT in the future?) this "live", portal report would be necessary. I suggest closing issue.

**Comment by remomueller** [comment]
Thanks, good point. Also, LOFT will be using the more dedicated AE module so that will help as well.
